Add netMHCIIpan 4.1 interface
KohlbacherLab/epytope pull request #66
Opened 2022-06-10 20:21 UTC by jonasscheid

This adds an interface for netMHCIIpan 4.1. 

Supported alleles are identical to 4.0, which is already implemented

Fixes #65

2022-06-10 20:26 UTC, jonasscheid commented on epytope/EpitopePrediction/External.py
> +    NETMHCIIPAN_4_0 = 4
I noticed that the enums were wrong here

2022-06-10 20:26 UTC, jonasscheid commented on epytope/EpitopePrediction/External.py
> +    NETMHCIIPAN_4_0 = 0
I noticed that the enums were wrong here

2022-06-13 15:01 UTC, christopher-mohr approved these changes
LGTM 👍, you could add it to the `CHANGELOG`.

2022-06-13 15:25 UTC, jonasscheid commented
👍 Will add it in #64 once this one is merged

2022-06-14 07:45 UTC, christopher-mohr requested changes
One small change

2022-06-14 07:45 UTC, christopher-mohr commented on CHANGELOG.md
> +- [#66](https://github.com/KohlbacherLab/epytope/pull/59) - Add interface for `NetMHCIIpan 4.1` [#65](https://github.com/KohlbacherLab/epytope/issues/65)
```suggestion
- [#66](https://github.com/KohlbacherLab/epytope/pull/66) - Add interface for `NetMHCIIpan 4.1` [#65](https://github.com/KohlbacherLab/epytope/issues/65)
```

2022-06-14 08:17 UTC, christopher-mohr approved these changes

2022-06-14 08:18 UTC, merged